from ajudante import Ajudante

class SeletorDeModos(object):

    def __init__(self, criador):
        self.criador = criador

    def setModo(self, modo):
        """Função responsável por setar o modo de tranmissao de dados.
        """

        self.criador.modo.setValor(modo)
        print('Trocando para modo ' + str(modo) + ' de transmissao!')

        sinaldo.setValor(modo)
        if modo == 0 or modo == 1:
            self.criador.tempo.setTransmissao(False)
            self.criador.altitudePressao.setTransmissao(False)
            self.criador.wow.setTransmissao(False)
            self.criador.velCas.setTransmissao(False)
            self.criador.pressaoEstaticar.setTransmissao(False)
            self.criador.pressaoTotalr.setTransmissao(False)
            self.criador.rpmD.setTransmissao(False)
            self.criador.posicaoX.setTransmissao(False)
            self.criador.posicaoY.setTransmissao(False)
            self.criador.altitude.setTransmissao(False)
            self.criador.rpmE.setTransmissao(False)
            self.criador.taxaGiroX.setTransmissao(False)
            self.criador.taxaGiroY.setTransmissao(False)
            self.criador.taxaGiroZ.setTransmissao(False)
            self.criador.aceleracaoX.setTransmissao(False)
            self.criador.aceleracaoY.setTransmissao(False)
            self.criador.aceleracaoZ.setTransmissao(False)
            self.criador.pitch.setTransmissao(False)
            self.criador.roll.setTransmissao(False)
            self.criador.pressaoEstatica.setTransmissao(False)
            self.criador.pressaoTotal.setTransmissao(False)
            self.criador.temperaturaBar.setTransmissao(False)
            self.criador.densidadeAr.setTransmissao(False)
            self.criador.altitudeRelativa.setTransmissao(False)
            self.criador.dadoTempoGPS.setTransmissao(False)
            self.criador.latitude.setTransmissao(False)
            self.criador.longitude.setTransmissao(False)
            self.criador.direcaoCurso.setTransmissao(False)
            self.criador.velocidade.setTransmissao(False)
            self.criador.velocidadeSubida.setTransmissao(False)
            self.criador.erroX.setTransmissao(False)
            self.criador.erroY.setTransmissao(False)
            self.criador.erroAltitude.setTransmissao(False)
            self.criador.erroVelocidade.setTransmissao(False)
            self.criador.erroVelocidadeSubida.setTransmissao(False)
            self.criador.latitudeRef.setTransmissao(False)
            self.criador.longitudeRef.setTransmissao(False)
            self.criador.distanciaAbsoluta.setTransmissao(False)
            self.criador.pressADC.setTransmissao(False)
            self.criador.pressTensao.setTransmissao(False)
            self.criador.pressaoDin.setTransmissao(False)
            self.criador.wowRaw.setTransmissao(False)
            self.criador.tempoVoo.setTransmissao(False)
            self.criador.distancia.setTransmissao(False)
            self.criador.distRef.setTransmissao(False)
            self.criador.sinaldo.setTransmissao(True)
            self.criador.nivelFixacao.setTransmissao(True)
            self.criador.agravante.setTransmissao(True)
            self.criador.ultimoTransmitido.setTransmissao(False)
        # 2 = Apenas transmitindo tempo, Vcas, HP, RPM e altitude(gps)
        elif modo == 2:
            self.criador.tempo.setTransmissao(True)
            self.criador.altitudePressao.setTransmissao(True)
            self.criador.wow.setTransmissao(True)
            self.criador.velCas.setTransmissao(True)
            self.criador.pressaoEstaticar.setTransmissao(False)
            self.criador.pressaoTotalr.setTransmissao(False)
            self.criador.rpmD.setTransmissao(True)
            self.criador.posicaoX.setTransmissao(False)
            self.criador.posicaoY.setTransmissao(False)
            self.criador.altitude.setTransmissao(True)
            self.criador.rpmE.setTransmissao(True)
            self.criador.taxaGiroX.setTransmissao(False)
            self.criador.taxaGiroY.setTransmissao(False)
            self.criador.taxaGiroZ.setTransmissao(False)
            self.criador.aceleracaoX.setTransmissao(False)
            self.criador.aceleracaoY.setTransmissao(False)
            self.criador.aceleracaoZ.setTransmissao(False)
            self.criador.pitch.setTransmissao(True)
            self.criador.roll.setTransmissao(True)
            self.criador.pressaoEstatica.setTransmissao(False)
            self.criador.pressaoTotal.setTransmissao(False)
            self.criador.temperaturaBar.setTransmissao(False)
            self.criador.densidadeAr.setTransmissao(False)
            self.criador.altitudeRelativa.setTransmissao(False)
            self.criador.dadoTempoGPS.setTransmissao(False)
            self.criador.latitude.setTransmissao(False)
            self.criador.longitude.setTransmissao(False)
            self.criador.direcaoCurso.setTransmissao(False)
            self.criador.velocidade.setTransmissao(False)
            self.criador.velocidadeSubida.setTransmissao(False)
            self.criador.erroX.setTransmissao(False)
            self.criador.erroY.setTransmissao(False)
            self.criador.erroAltitude.setTransmissao(False)
            self.criador.erroVelocidade.setTransmissao(False)
            self.criador.erroVelocidadeSubida.setTransmissao(False)
            self.criador.latitudeRef.setTransmissao(False)
            self.criador.longitudeRef.setTransmissao(False)
            self.criador.distanciaAbsoluta.setTransmissao(False)
            self.criador.pressADC.setTransmissao(False)
            self.criador.pressTensao.setTransmissao(False)
            self.criador.pressaoDin.setTransmissao(False)
            self.criador.wowRaw.setTransmissao(False)
            self.criador.tempoVoo.setTransmissao(False)
            self.criador.distancia.setTransmissao(False)
            self.criador.distRef.setTransmissao(False)
            self.criador.sinaldo.setTransmissao(True)
            self.criador.nivelFixacao.setTransmissao(True)
            self.criador.agravante.setTransmissao(True)
            self.criador.ultimoTransmitido.setTransmissao(False)
        elif (modo == 3) or (modo == 4):
            self.criador.tempo.setTransmissao(True)
            self.criador.altitudePressao.setTransmissao(True)
            self.criador.wow.setTransmissao(True)
            self.criador.velCas.setTransmissao(True)
            self.criador.pressaoEstaticar.setTransmissao(True)
            self.criador.pressaoTotalr.setTransmissao(True)
            self.criador.rpmD.setTransmissao(True)
            self.criador.posicaoX.setTransmissao(True)
            self.criador.posicaoY.setTransmissao(True)
            self.criador.altitude.setTransmissao(True)
            self.criador.rpmE.setTransmissao(True)
            self.criador.taxaGiroX.setTransmissao(False)
            self.criador.taxaGiroY.setTransmissao(False)
            self.criador.taxaGiroZ.setTransmissao(False)
            self.criador.aceleracaoX.setTransmissao(False)
            self.criador.aceleracaoY.setTransmissao(False)
            self.criador.aceleracaoZ.setTransmissao(False)
            self.criador.pitch.setTransmissao(True)
            self.criador.roll.setTransmissao(True)
            self.criador.pressaoEstatica.setTransmissao(False)
            self.criador.pressaoTotal.setTransmissao(False)
            self.criador.temperaturaBar.setTransmissao(False)
            self.criador.densidadeAr.setTransmissao(False)
            self.criador.altitudeRelativa.setTransmissao(False)
            self.criador.dadoTempoGPS.setTransmissao(False)
            self.criador.latitude.setTransmissao(False)
            self.criador.longitude.setTransmissao(False)
            self.criador.direcaoCurso.setTransmissao(False)
            self.criador.velocidade.setTransmissao(False)
            self.criador.velocidadeSubida.setTransmissao(False)
            self.criador.erroX.setTransmissao(False)
            self.criador.erroY.setTransmissao(False)
            self.criador.erroAltitude.setTransmissao(False)
            self.criador.erroVelocidade.setTransmissao(False)
            self.criador.erroVelocidadeSubida.setTransmissao(False)
            self.criador.latitudeRef.setTransmissao(False)
            self.criador.longitudeRef.setTransmissao(False)
            self.criador.distanciaAbsoluta.setTransmissao(False)
            self.criador.pressADC.setTransmissao(False)
            self.criador.pressTensao.setTransmissao(False)
            self.criador.pressaoDin.setTransmissao(False)
            self.criador.wowRaw.setTransmissao(False)
            self.criador.tempoVoo.setTransmissao(False)
            self.criador.distancia.setTransmissao(False)
            self.criador.distRef.setTransmissao(False)
            self.criador.sinaldo.setTransmissao(True)
            self.criador.nivelFixacao.setTransmissao(True)
            self.criador.agravante.setTransmissao(True)
            self.criador.ultimoTransmitido.setTransmissao(False)